In [10]:
from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import cross_val_score
import numpy as np
from sklearn.metrics import make_scorer, mean_squared_error

In [11]:
text = [
    "Machine learning is fascinating",
    "Deep learning powers many AI applications",
    "Natural language processing is a key AI field",
    "Big data plays a significant role in AI",
    "Python is a popular language for data science"
]

In [12]:
vectorizer = CountVectorizer()
X = vectorizer.fit_transform(text)

In [13]:
print("features:", vectorizer.get_feature_names_out())
print("matrix:\n", X.toarray())

features: ['ai' 'applications' 'big' 'data' 'deep' 'fascinating' 'field' 'for' 'in'
 'is' 'key' 'language' 'learning' 'machine' 'many' 'natural' 'plays'
 'popular' 'powers' 'processing' 'python' 'role' 'science' 'significant']
matrix:
 [[0 0 0 0 0 1 0 0 0 1 0 0 1 1 0 0 0 0 0 0 0 0 0 0]
 [1 1 0 0 1 0 0 0 0 0 0 0 1 0 1 0 0 0 1 0 0 0 0 0]
 [1 0 0 0 0 0 1 0 0 1 1 1 0 0 0 1 0 0 0 1 0 0 0 0]
 [1 0 1 1 0 0 0 0 1 0 0 0 0 0 0 0 1 0 0 0 0 1 0 1]
 [0 0 0 1 0 0 0 1 0 1 0 1 0 0 0 0 0 1 0 0 1 0 1 0]]


In [14]:
y = np.array([1, 2, 3, 4, 5]) 

In [15]:
pipeline = Pipeline([
    ('vectorizer', CountVectorizer(ngram_range=(1, 2))),
    ('regression', LinearRegression())
])

In [16]:
scorer = make_scorer(mean_squared_error)
scores = cross_val_score(pipeline, text, y, cv=5, scoring=scorer)
print(f"Validation score: {scores.mean():.2f} (+/- {scores.std() * 2:.2f})")

Validation score: 3.03 (+/- 5.83)
